api.get.films:
    path:       /api/films
    defaults: { _controller: AppBundle:Default:getFilms }
    methods:    [GET]
api.get.film:
    path:       /api/film/{id}
    defaults: { _controller: AppBundle:Default:getFilm }
    methods:    [GET]
api.delete.film:
    path:       /api/film/{id}
    defaults: { _controller: AppBundle:Default:deleteFilm }
    methods:    [DELETE]
api.post.film:
    path:       /api/film
    defaults: { _controller: AppBundle:Default:postFilm }
    methods:    [POST]
api.update.film:
    path:       /api/film/{id}
    defaults: { _controller: AppBundle:Rest:updateFilm }
    methods:    [PUT]
api.get.actors:
    path:       /api/actors
    defaults: { _controller: AppBundle:Default:getActors }
    methods:    [GET]